import Head from 'next/head'
import { Typography, Button } from '@mui/material'
import styles from '@/styles/Home.module.css'

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Typography>New Page</Typography>
        <Button>Click me</Button>
      </main>
    </>
  )
}

export default Home
